# This is a sample config for use with the layer creator to be more specific about the bucket creation and policy

#LayerName:
#  MyLayer
#Description:
#  Layer created with layer builder
#Content:
#  S3Key:
#    Layer
#  S3ObjectVersion:
#    Latest
#CompatibleRuntimes:    -- 'nodejs'|'nodejs4.3'|'nodejs6.10'|'nodejs8.10'|'java8'|'python2.7'|'python3.6'|'python3.7'|'dotnetcore1.0'|'dotnetcore2.0'|'dotnetcore2.1'|'nodejs4.3-edge'|'go1.x'|'ruby2.5'|'provided',
#  -
#    python3.7
#LicenseInfo:
#  N/A

LayerName:
  MyLayer
Description:
  Layer created with layer builder
Content:
  S3Key:
    layer.zip
CompatibleRuntimes:
  -
    python3.7
LicenseInfo:
  N/A