# This is a sample config for use with the layer creator to be more specific about the bucket creation and policy

#ACL: "This is a sample ACL"
#CreateBucketConfiguration:
#  LocationConstraint:
#    "us-east-2"
#GrantFullControl:
#  -
#    "sample_user"
#GrantRead:
#  -
#    "sample_user"
#GrantReadACP:
#  -
#    "sample_user"
#GrantWrite:
#  -
#    "sample_user"
#GrantWriteACP:
#  -
#    "sample_user"
#ObjectLockEnabledForBucket: False

CreateBucketConfiguration:
  LocationConstraint:
    "us-east-2"